### ISSUE TITLE
Identify DIACL concepts which map to the same concept set?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/diacl#1]
DIACL contains concepts from multiple concept lists, but does not merge or identify these. The lexibank CLDF could either do this (once we have concepticon mappings for all lists), or just do what DIACL does. Since a CLDF Wordlist does not have a many-to-many relation between lexemes and concepts, this would result in a multiplication of mostly identical forms - just associated to different concepts (which are not so different again). Also, this multiplication of forms would lead to a multiplication of cognate sets.

So using the DIACL data would typically have to start with filtering everything by concept list. But I guess that's still preferable to more and complex code doing the merging when creating the CLDF?

**Comment by LinguList** [comment]
The question I am asking myself is: does diacl clearly distinguish doculects? I mean, if they don't, and we have "Hindi", in 5 sublists, but from 3 different sources, there would not be a real duplication, right? 

And as to colexifications: I think our code now avoids that synonyms are duplicated, so this should not have an impact there.

**Comment by xrotwang** [comment]
Oh, no, DIACL does deduplicate the lexemes. So they'd have lexeme "Hand" from German just once, but associate it with concept "Hand" in Swadesh 100 **and** concept "Hand" in Swadesh 200. Now, since we don't have this option in CLDFWordlist, we'd just add **two** forms "Hand" to capture both associations.

Alternatively, we could merge the DIACL concepts, i.e. have only one concept "Hand", merged from the two via identical `CONCEPTICON_ID`. And consequently only have one form "Hand", related to the merged concept.

**Comment by xrotwang** [comment]
So I guess the question is whether we want to "be loyal to the source" or "provide a service to the user" - because the user of the data would presumably prefer the merged concepts.

**Comment by LinguList** [comment]
Puh, I'd say, I may prefer the merge variant.

**Comment by LinguList** [comment]
In some sense, if they associate the "hand" lexeme with multiple lists, they do something like a concepticon there, right?

**Comment by LinguList** [comment]
only that our concepticon may be a bit stricter.

**Comment by xrotwang** [comment]
What makes merging concepts somewhat problematic (although I don't know how often this may be a problem): Cognate sets have to be computed from etymologies - which are networks of **lexemes**, by taking concept associations into account.

So it could happen that we get different cognate sets after merging.

**Comment by LinguList** [comment]
Okay, I would say: the primary purpose is the lexical data, as the cognate sets are of little use, as they are not provided with phonetic transcriptions. So the preference would be lexemes over cognate sets here...

**Comment by xrotwang** [comment]
So you say we should merge concepts, right? Even if this means that cognate sets may be slightly distorted?
I tend to agree, in particular because there is no simple, clear way to determine cognate sets in the source data to begin with. Thus we'd only add a bit of complexity to an already complex process in order to make the resulting data easier to understand.

**Comment by LinguList** [comment]
Yes. BTW: I'd also suggest to merge the conceptlists then: instead of linking them all, rather merge them, put identical concept glosses to the same slot, but maybe mark in an extra column, where they are assigned to. This will greatly facilitate the procedure. 

Alternatively: link all lists separately, merge them into one, where you provide tthe origin, based on our concepticon mapping.

But it would be easier to just submit one list to concepticon, I guess...

**Comment by xrotwang** [comment]
I was going to go with the second option - since this seems more transparent to me:
- add multiple concept lists to Concepticon (Concepticon is more concerned with being faithful to the source than lexibank, which is more about providing comparable lexical dta)
- merge these lists into one `etc/concepts.csv` which is then used to merge concepts in the lexibank dataset.

This means that all judgement calls are concentrated in lexibank, rather than being scattered around in multiple repositories.

**Comment by xrotwang** [comment]
@LinguList @chrzyki here's the list of "map-to-broader concept" items for the DIACL concepts:
```
WE (EXCLUSIVE) -> WE
WE (INCLUSIVE) -> WE
COOKED RICE -> RICE
PADDY FIELD -> FIELD
SEA -> SEA OR OCEAN
BLACK -> BLACK OR DARK
FIELD (UPLAND) -> FIELD
FAT (ORGANIC SUBSTANCE) -> ORGANIC FAT OR OIL
MEAT -> FLESH OR MEAT
OCEAN -> SEA OR OCEAN
```

Merge or not?

**Comment by xrotwang** [comment]
I guess the `FIELD` and `WE` mergers could be problematic; especially the `WE`, because here, both finer concepts may be present in the same source concept list, so it would introduce quite a few fake synonyms.

**Comment by chrzyki** [comment]
Agree with the fake synonymy problem, there's quite a difference there. With the others I'm not quite sure, really, they seem distinct enough to me to warrant individual concepts instead of a broader mapping, but then again this approach of course doesn't scale well.

**Comment by LinguList** [comment]
I'd say: if these are not true differences, it's no problem: they'll show up as colexifications, and this won't hurt us, right? And in the paper, we can mention, that our analysis shows that we can't really replicate this, because they put the swadesh term in a different list.

**Comment by LinguList** [comment]
Later, when using lexibank, one could make customized concept lists by querying swadesh including fuzzy meanings. In this way, one would allow for some degree of fuzziness, as long as it is not too much, etc.

As a little task, we could compute, by using the union / intersection approach of our API in concepticon, sublist statistics of the clics data with respect to the "famous" Swadesh lists.

**Comment by xrotwang** [comment]
Well, the whole issue came up because [kravíṣ-](https://diacl.ht.lu.se/Lexeme/Details/70632) is said to be "Swadesh cognate" with ['kreas](https://diacl.ht.lu.se/Lexeme/Details/33836). Unfortunately the former is only linked to ["meat" in the Culture words for Indo-European list](https://diacl.ht.lu.se/WordListItem/Details/3052), while the latter is only linked to ["meat/flesh" in Swadesh 100](https://diacl.ht.lu.se/WordListItem/Details/1053). Since they use this example to explain "Swadesh cognate", it would seem that they claim the two words express the same concept.

So if we want to make this example a "real" cognate set in the CLDF dataset, some "broadening" has to happen somewhere. Of course, this could also be used to show a good design decision in the CLDF Cognacy component: We could only use the broadened concepts when computing cognate sets, but still leave the lexemes related to the more specific concepts. So in the strict sense, they'd be cross-semantic cognates.

**Comment by LinguList** [comment]
Swadesh cognate is in this sense not the same as "meaning same concepticon-id", but meaning judged same by people. In fact, I do not like their distinction between etymology and cognate set. I'd say: etymologies are cognate sets, and the Swadesh cognate definition is based on how one defines one's meaning slots. As we define them by concepticon, they'd be discarded, but we could show that we can easily reach the "broadening", via pyconcepticon, but in cldf, we keep only etymologies as the "true" cognate sets, which is anyway the definition of a cognate in classical linguistics.

**Comment by xrotwang** [comment]
it would be cool, though, - as a way to show off CLDF - to include both, the "Swadesh cognates" and the Etymologies in the same dataset. This would be possible, and the cognate sets could be annotated in the `CognatesetsTable` accordingly - as `Swadesh` or `Etymology`.

**Comment by LinguList** [comment]
Yes, then I suggest, to run the "intersection" command of the pyconcepticon api on the whole dump of Diacl and assemble all concepts falling under that roof into the same slot. This can be done when compiling for lexibank, right?

**Comment by xrotwang** [comment]
I use the API to assemble a "broadening" map:
```python
        broader_concept_map = {}
        for cid in list(concepts.keys()):
            for relcid, _ in self.concepticon.relations.iter_related(cid, 'broader'):
                if relcid in concepts:
                    broader_concept_map[cid] = relcid
                    break
```

**Comment by LinguList** [comment]
nice.

**Comment by xrotwang** [comment]
Hm. Would have been nice. Unfortunately, it turns out that even now I don't get the cognacy, because the etymologies are not linked up: What should have been the link is actually **two different** lexemes in DIACL:
- *'kreas* is linked to [*kreuh2-](https://diacl.ht.lu.se/Lexeme/Details/31282)
- *kravíṣ-* is linked to [*kreuh₂-s-](https://diacl.ht.lu.se/Lexeme/Details/70633)

Pretty unsatisfying.

**Comment by LinguList** [comment]
The question is the search depth, of course, we use 3 in [compare_conceptlists](https://github.com/concepticon/pyconcepticon/blob/a876fb9068b4d08cbd83c54ee44f7adcb5e9ce7f/src/pyconcepticon/models.py#L256), but we can later just compare the lists, when they are all mapped.

**Comment by LinguList** [comment]
Wow. It's a bad idea to have derived forms in etymologies anyway, unless they are linked more (-s- indicates a suffix). How come they bring this as example in their description, if it doees't work on the app?

**Comment by xrotwang** [comment]
Yes, that has me scratching my head, too. Probably just shows that having a database doesn't mean your work is data-driven :)

**Comment by LinguList** [comment]
okay, this is the api on concepticon-dev:

```
$ concepticon union `ls concepticondata/conceptlists/Carling-2017*.tsv`
```

And here's the result.

[carling-full.txt](https://github.com/lexibank/diacl/files/2845155/carling-full.txt)

**Comment by LinguList** [comment]
There are not that many cases, but they are typical...
