### ISSUE TITLE
smart splitters of linguistic entries

### ISSUE THREAD

**Issue by LinguList** [lexibank/diacl#2]
Diacl is particularly ambitious for automatic parsing from value to form: they have up to 5 entries, at times even more, separated by different entries, in the cells. We thus need to define the splitting function smartly, and I recommend to only take the first of the forms in the data, not because I think that is the best form, but since it's more principled than doing a random selection or something else. What is clear: we can't handle this manually, but we need to make a thorough check of the data to avoid that, for example, all splitters are identified.

**Comment by xrotwang** [comment]
Hm. Unfortunately the section on *Policies for orthography, base form of lemmas, and hyphenation* [here](https://diacl.ht.lu.se/Content/documents/DiACL-lexicology.pdf) does not say anything about multiple forms in the Transcription field.
