### ISSUE TITLE
identify more languages

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/diacl#5]

**Comment by chrzyki** [comment]
Has this been tackled in the last couple of commits?

**Comment by xrotwang** [comment]
I merged the PR where @SimonGreenhill added two more. Dunno whether we can do better right now. The bulk of unidentified languages are Romani varieties which don't have specific Glottolog matches.

**Comment by SimonGreenhill** [comment]
yeah, I think so too. Lots of "old" varieties as well.
