### ISSUE TITLE
Update language mappings (of Romani dialects) when Glottolog 3.5 is released

### ISSUE THREAD

**Issue by xrotwang** [lexibank/diacl#6]
Glottolog 3.5 will contain a lot more Romani dialects (see https://github.com/clld/glottolog/pull/354), so the mappings in `etc/languages.csv` can be completed once the next version of Glottolog is released.

**Comment by chrzyki** [comment]
Done in https://github.com/lexibank/diacl/commit/ba8dda7fdad90da388e0387f608f6b3cf42a619b.
